CREATE TABLE biens(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(720),
  price MEDIUMINT NOT NULL DEFAULT "0",
  price_type VARCHAR(500) NOT NULL DEFAULT "TTC",
  offer VARCHAR(500) NOT NULL DEFAULT "achat",
  image TEXT,
  location TEXT,
  nb_rooms TINYINT NOT NULL DEFAULT "0",
  nb_beds TINYINT NOT NULL DEFAULT "0",
  nb_bathrooms TINYINT NOT NULL DEFAULT "0",
  equipments LONGTEXT,
  creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)